// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwgJWQJWK4Y0NoMU9fAKG8PzMyGSDQTFU',
    appId: '1:223831559291:web:b7b88589ceda73554c66de',
    messagingSenderId: '223831559291',
    projectId: 'smile-a55e7',
    authDomain: 'smile-a55e7.firebaseapp.com',
    storageBucket: 'smile-a55e7.appspot.com',
    measurementId: 'G-24WCH97K52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBqrsJnbIrgJM-W4aqN81GSyxceq5lisA',
    appId: '1:223831559291:android:8f05070cf7cd9b424c66de',
    messagingSenderId: '223831559291',
    projectId: 'smile-a55e7',
    storageBucket: 'smile-a55e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS0atxQtzFF2Ega8WvG_8sAJW-qktcn9k',
    appId: '1:223831559291:ios:c02664c024d4019f4c66de',
    messagingSenderId: '223831559291',
    projectId: 'smile-a55e7',
    storageBucket: 'smile-a55e7.appspot.com',
    iosBundleId: 'com.example.smile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS0atxQtzFF2Ega8WvG_8sAJW-qktcn9k',
    appId: '1:223831559291:ios:a4853e30092bef594c66de',
    messagingSenderId: '223831559291',
    projectId: 'smile-a55e7',
    storageBucket: 'smile-a55e7.appspot.com',
    iosBundleId: 'com.example.smile.RunnerTests',
  );
}
